databases:
- name: postgres
  ipAllowList: []

services:
- type: web
  name: rails
  env: ruby
  plan: free
  buildCommand: "./bin/render-build.sh"
  startCommand: bundle exec rails s 
  envVars:
  - key: DATABASE_URL
    formDatabase:
      name: postgres
      property: connectionString
  - key: REDI_HOST
    fromServices: 
      name: rails
      type: redis
      property: hostport
  - key: RAILS_MASTER_KEY
    sync: false
- type: redis
  name: redis
  env: ruby
  ipAllowList: []
  plan: free
  maxmemoryPolicy: noeviction
